-- Migration 009: Add wit_line column to job_evaluations
-- wit_line is a 3-5 word punchy quip generated by the evaluator LLM

ALTER TABLE job_evaluations ADD COLUMN IF NOT EXISTS wit_line TEXT;

-- Backfill from raw_response JSONB for existing rows
UPDATE job_evaluations
SET wit_line = NULLIF(TRIM(raw_response->>'wit_line'), '')
WHERE raw_response IS NOT NULL
  AND raw_response->>'wit_line' IS NOT NULL
  AND TRIM(raw_response->>'wit_line') <> '';
